### PR TITLE
[US-234] Update form example to add a submit button

### PR DESCRIPTION
**Pull request by 3ace**

### CODE REVIEW

**Review by sampila — CHANGES_REQUESTED** [review]
Probably best to separate the example? like form_external_submit.go?

**Comment by gunnsth** [comment]
Yeah might be good to separate.  The other one is just focused on adding some basic things to the form but then this one adds the submit functionality which I am not sure if is very commonly used.
Then the use case is also clear and easier to find.

**Comment by 3ace** [comment]
understood, I'll update the PR then. Thanks for the input

**Comment by 3ace** [comment]
@sampila @gunnsth I've updated this PR to use the new submit functionality introduced in unipdf v3.54

**Review by sampila — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
